version: '3'

services:
  php:
    container_name: myblog-php
    image: php:7.2-apache
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    container_name: myblog-mysql
    image: mysql:5.7.23
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myblog-bd
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: always

volumes:
  db_data: