version: '3'

services:
  php:
    container_name: myblog-php
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./public:/var/www/html
      - ./:/var/www
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    #restart: always
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    container_name: myblog-mysql
    image: mysql:5.6.42
    volumes:
      - myblog_db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myblog_db
    #restart: always

volumes:
  myblog_db_data: